version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
    - "8001:80"
    depends_on:
    - app
    volumes:
    - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    - ./public:/var/www/html/public:cached
  app:
    build: ./docker/app
    depends_on:
    - mysql
    volumes:
    - .:/var/www/html:cached
    - ./php.ini/:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
  composer:
    build: ./docker/composer
    volumes:
      - './:/data'
volumes:
  mysql-data:

